New partner footer on some pages and adjustments to the banner
linea-it/pzserver_app pull request #311
Opened 2024-09-13 04:44 UTC by jandsonrj

Addition of new footer on About, Tutorials and Contact pages, and small adjustment to banner size + removal of social media

2024-09-19 17:25 UTC, gschwend approved these changes
tested on localhost

2024-09-19 17:27 UTC, gschwend requested changes
@jandsonrj please solve the Build and Push Docker Images check before merging this branch

2024-09-26 20:40 UTC, jandsonrj commented
> @jandsonrj please solve the Build and Push Docker Images check before merging this branch

I fixed the issues caused by ESLint mentioned, could you please validate again?

2024-10-10 16:43 UTC, gschwend commented
@jandsonrj não consigo abrir no localhost aqui, pode dar uma ajudinha? 
![image](https://github.com/user-attachments/assets/42db2a6c-a7d2-4f2e-9d04-65f27a200215)

2024-10-10 16:46 UTC, jandsonrj commented
> @jandsonrj não consigo abrir no localhost aqui, pode dar uma ajudinha? ![image](https://private-user-images.githubusercontent.com/9534570/375469906-42db2a6c-a7d2-4f2e-9d04-65f27a200215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Nzg5OTMsIm5iZiI6MTcyODU3ODY5MywicGF0aCI6Ii85NTM0NTcwLzM3NTQ2OTkwNi00MmRiMmE2Yy1hN2QyLTRmMmUtOWQwNC02NWYyN2EyMDAyMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMTY0NDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDBjYWFjYjlhNDgwNzNiOWVkZTdhZTljN2E0NjM3NWMzYTkwMjQ1ZjU4YTQ5YjM1YTkwZTc1YmQ3ZTJkYzA1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4xC7sZOUfnljxMTM3FANAziFl8jMcxU-gw0jIG3CI4Y)

simm, vamos lá: https://meet.google.com/wqo-xkxo-uoo

2024-10-10 17:51 UTC, gschwend commented
abrindo pelo devcontainer no VS Code:
![image](https://github.com/user-attachments/assets/96591ce5-4141-4654-a494-5b307194f96d)
@crisingulani pode dar uma olhadinha? :)

2024-10-11 13:54 UTC, luigilcsilva commented
Consegui abrir o pz-server no meu localhost aqui. Fiz o seguinte.

1) Comando: docker compose up.
2) Erro: Unhandled Runtime Error
	Error: Request failed with status code 400.
3) Comando: docker compose build.
4) Comando: docker compose up.
5) Erro: Unhandled Runtime Error
	Error: Request failed with status code 400.
6) Abri o localhost em uma aba anônima do Chrome. Funcionou direto, sem erro.

2024-10-11 14:46 UTC, luigilcsilva approved these changes
Tested in localhost. The footer is ok in the three pages (about, tutorials and contact). All the links are working too.

2024-10-15 12:18 UTC, gschwend commented
@crisingulani eu segui o passo-a-passo do Luigi no comentário acima e ainda não consigo. Alguma dica? Segue o último erro: 
![image](https://github.com/user-attachments/assets/bc663754-956d-472d-9526-6349fc1a7223)

2024-10-15 13:20 UTC, crisingulani commented
> @crisingulani eu segui o passo-a-passo do Luigi no comentário acima e ainda não consigo. Alguma dica? Segue o último erro: ![image](https://private-user-images.githubusercontent.com/9534570/376604303-bc663754-956d-472d-9526-6349fc1a7223.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTg2NDcsIm5iZiI6MTcyODk5ODM0NywicGF0aCI6Ii85NTM0NTcwLzM3NjYwNDMwMy1iYzY2Mzc1NC05NTZkLTQ3MmQtOTUyNi02MzQ5ZmMxYTcyMjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMTMxOTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRiZDYxZDE3OGE2NGE2NTQ5MTk1MmE4N2NjZTc3ZjM2N2U1Mzg4YmM2ZjU4ZjgxNWM0MDM2OGQ4NTVjYmUxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.uxaLrg7K0TlxZuucT1KwYlvbTqYS9QFJ5CQIp_9W18I)

@gschwend em qual momento ocorre o erro?

2024-12-04 14:47 UTC, crisingulani approved these changes

2024-12-04 20:57 UTC, gschwend approved these changes
tested on localhost

2024-12-04 20:59 UTC, merged